# 난수

## #01. 작업준비

### 패키지 참조

In [2]:
import tensorflow as tf

## #02. 균등 분포 난수

일반적으로 각 이벤트의 결과값을 알 수 없는 경우 미래에 발생할 이벤트의 결과값 $x$ 가 각 예상되는 범위별로 균등한 확률로 일어날 것이라고 예상될 때 사용.

### 1) 균등 분포 난수의 사용 예
주사위에 대한 확률
- 200번을 던지고 201번째 주사위를 던진다고 했을 때 201번째 결과값은 앞의 1에서 200번까지 결과값에 영향을 받지 않는다.
- 201번째 결과값이 1,2,3,4,5,6 각각의 결과값으로 나올 확률은 6분의 1이며 이는 앞의 1~200번째 결과값에 영향을 받아 줄어들거나 늘어나지 않는다는 것이다.
- 이처럼 미래 결과값이 경험적으로 알 수 없을 상황에서 사용하는 것이 균등분포이다. 

### 2) 균등 분포 난수 실험
#### 스칼라 형태의 균등 분포 난수 

In [4]:
uni_rnd1 = tf.random.uniform(shape=[], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd1)

81


#### 벡터 형태의 균등 분포 난수

In [6]:
uni_rnd2 = tf.random.uniform(shape=[5], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd2)

[92 53 34 50 34]


#### 행렬 형태의 균등 분포 난수

In [10]:
uni_rnd3 = tf.random.uniform(shape=[2,3], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd3)

[[97 82 68]
 [80 81 6]]


#### 텐서 형태의 균등 분포 난수

In [12]:
uni_rnd4 = tf.random.uniform(shape=[2,3,4], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd4)

[[[5 58 3 37]
  [81 38 46 47]
  [77 32 59 48]]

 [[55 49 99 85]
  [22 99 4 13]
  [0 63 88 21]]]


### 3) 렌덤값을 갖는 행렬 곱 예시

#### 랜덤값을 갖는 3행 2열의 행렬을 변수 x로 정의

In [13]:
x = tf.Variable(tf.random.uniform([3,2]))
tf.print(x)

[[0.706019759 0.0474249125]
 [0.704897642 0.483775973]
 [0.461128712 0.0591117144]]


#### 랜덤값을 갖는 2행1열의 행렬을 변수 y로 정의

In [15]:
y = tf.Variable(tf.random.uniform([2,1]))
tf.print(y)

[[0.815526366]
 [0.32887125]]


#### 행렬곱에 대한 연산을 수행하는 노드 정의

In [16]:
expr = tf.matmul(x,y)
tf.print(expr)

[[0.591374397]
 [0.733962595]
 [0.395502776]]


## #03. 정규 분포 난수

정규분포란 과거의 축적된 경험적 데이터를 이미 보유하고 있는 상태에서 이용하여 미래에 발생할 결과값 $x$ 의 각 예상되는 범위별로 발생될 확률을 어느 정도 추정할 수 있을 때 사용

### 1) 정규 분포 난수의 사용 예
####  매장의 매출액 예측
- 이전 3개월의 매출이 2천만원, 2천백만원, 2천2백원 발생한 경우 평균이나 범위에 대한 예측이 가능하다.
- `평균` 에 대한 예측 -> 이번달 매출은 과거 3개월의 매출평균인 2천백만원으로 예측
- `범위` 에 대한 예측 -> 최소 2천만원 ~ 최대 2천2백만원까지 매출이 발생할 수 있다는 예상이 가능함.

#### 로또 추첨
- 64개의 공 중에서 하나를 랜덤으로 추출하면, 두 번째 랜덤 범위는 첫 번째 추출된 공을 제외한 범위 안에서 생성된다.
- 만약 로또 추첨시 하나의 공을 뽑아 번호를 확인하고 그 공을 다시 추첨 대상에 포함시켰다면 균등분포 난수가 된다.

### 2) 정규 분포 난수 실험
정규 분포 난수를 생성할 때는 평균(mean)과 표준편차(stddev) 를 지정해야 한다.

#### 스칼라 형태의 정규 분포 난수

In [18]:
normal_rnd1 = tf.random.normal(shape=[], mean=0.0, stddev=1.0)
tf.print(normal_rnd1)

-0.0532309189


#### 벡터 형태의 정규 분포 난수

In [19]:
normal_rnd2 = tf.random.normal(shape=[5], mean=0.0, stddev=1.0)
tf.print(normal_rnd2)

[-0.20347105 0.927871 1.88454533 -0.243177444 0.121433325]


#### 행렬 형태의 정규 분포 난수

In [20]:
normal_rnd3 = tf.random.normal(shape=[2,3], mean=0.0, stddev=1.0)
tf.print(normal_rnd3)

[[1.16339564 0.565056 -1.01632333]
 [-0.415462375 -1.21506691 -1.25226605]]


#### 텐서 형태의 정규 분포 난수

In [21]:
normal_rnd4 = tf.random.normal(shape=[2,3,4], mean=0.0, stddev=1.0)
tf.print(normal_rnd4)

[[[-0.602066875 -1.43345165 -1.11798429 0.853389561]
  [-0.0208575409 -1.16657269 2.09116292 1.04419255]
  [-1.08708918 -0.941793 -0.283036977 1.1975621]]

 [[-0.841952562 0.86236465 0.443042964 -1.03896904]
  [0.336122 -0.427560121 0.141951695 1.43265665]
  [0.675829113 0.909763873 -0.561516404 -0.0455188677]]]
