# 지도학습(1) 회귀

지도학습은 크게 `회귀`와 `분류`로 나눌 수 있다.

## #01. 작업준비

### 패키지 가져오기

In [1]:
from pandas import read_excel
from sklearn.linear_model import LinearRegression

## #02. 단순선형회귀

###  데이터 가져오기

자동차의 속도(speed)에 따른 제동거리(dist)조사 데이터

In [5]:
origin = read_excel("https://data.hossam.kr/E04/cars.xlsx")
origin.head()

speed  dist
0      4     2
1      4    10
2      7     4
3      7    22
4      8    16

### 분석 알고리즘을 포함하고 있는 객체 생성

In [6]:
model = LinearRegression()

### 분석모델을 학습시킴

`fit(독립변수, 종속변수)` 형태로 사용

직접 데이터를 파라미터로 전달할 경우 
1. 2차원 배열(numpy)설정 = 2차원배열(=matrix), 3차원배열(=Tensor)
2. 완전한 데이터 프레임 형태로 전달

In [7]:
fit = model.fit(origin[['speed']], origin[['dist']])
fit

LinearRegression()

### 학습결과 확인

직선의 기울기

In [8]:
# 2차원배열의 인덱스를 주의해보자!
coef = fit.coef_
coef

array([[3.93240876]])

In [9]:
# 2차원 배열이므로
coef[0][0]

3.932408759124089

절편

In [10]:
intercept = fit.intercept_
intercept

array([-17.57909489])

In [11]:
intercept[0]

-17.579094890510973

### 회귀식 추정

In [12]:
print('y = {0:.2f} * X + {1:.2f}'.format(coef[0][0], intercept[0]))

y = 3.93 * X + -17.58


### 설명력 (r-score)

In [13]:
#회귀분석 ols는 summary()를 출력하면 모두 다 볼 수 있지만, 머신러닝은 summary()가 없으므로 일일이 다 확인해봐야 한다!
rscore = fit.score(origin[['speed']], origin[['dist']])
rscore

0.6510793807582509

In [14]:
print('설명력: {: .1%}'.format(rscore))

설명력:  65.1%


### 회귀분석 결과 활용

#### 모델을 활용한 결과값 얻기

In [15]:
# 머신러닝은 2차원 배열이므로 [[]] 로 써야한다.
# Error(does not have valid feature names): 되도록 데이터프레임을 만들어서 넣어달라는 경고 메세지
speed = [[10],[15],[20],[25],[30],[35],[40]]
pred = fit.predict(speed)
pred

c:\Users\hanjieun_2\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[ 21.7449927 ],
       [ 41.4070365 ],
       [ 61.06908029],
       [ 80.73112409],
       [100.39316788],
       [120.05521168],
       [139.71725547]])

## #03. 다중선형회귀

### 데이터 가져오기

In [17]:
origin = read_excel("https://data.hossam.kr/E04/boston.xlsx")
origin.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  CAT. MEDV  
0  396.90   4.98  24.0          0  
1  396.90   9.14  21.6          0  
2  392.83   4.03  34.7          1  
3  394.63   2.94  33.4          1  
4  396.90   5.33  36.2          1

### 데이터 전처리

머신러닝에서 데이터전처리라 함은 독립변수와 종속변수를 분리하는 과정을 의미

#### 독립변수 추출

In [21]:
x_train = origin[["CRIM", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "TAX", "PTRATIO", "B", "LSTAT"]]
x_train.head()

CRIM  INDUS  CHAS    NOX     RM   AGE     DIS  TAX  PTRATIO       B  \
0  0.00632   2.31     0  0.538  6.575  65.2  4.0900  296     15.3  396.90   
1  0.02731   7.07     0  0.469  6.421  78.9  4.9671  242     17.8  396.90   
2  0.02729   7.07     0  0.469  7.185  61.1  4.9671  242     17.8  392.83   
3  0.03237   2.18     0  0.458  6.998  45.8  6.0622  222     18.7  394.63   
4  0.06905   2.18     0  0.458  7.147  54.2  6.0622  222     18.7  396.90   

   LSTAT  
0   4.98  
1   9.14  
2   4.03  
3   2.94  
4   5.33

#### 종속변수 추출

In [22]:
y_train = origin[['MEDV']]
y_train.head()

MEDV
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

### 분석 수행

In [23]:
# 객체 만들기
model = LinearRegression()

#분석수행
fit = model.fit(x_train, y_train)

print('계수:', fit.coef_)
print('절편:', fit.intercept_)
print('설명력:', fit.score(x_train, y_train))

print('y = {0:.2f} * X + {1:.2f}'.format(coef[0][0], intercept[0]))

계수: [[-6.18750142e-02 -7.22462346e-02  3.12288964e+00 -1.58299544e+01
   4.28468563e+00 -8.28081464e-03 -1.25415352e+00  2.87273861e-03
  -9.65514253e-01  8.56492285e-03 -5.09092893e-01]]
절편: [30.55853145]
설명력: 0.7249622391093025
y = 3.93 * X + -17.58
